name: Pushing a very productive work
run-name: ${{ github.actor }} is making a very productive work

on:
  push:
    branches: [working]
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  onAndOffFunction:
    if: vars.WORKFLOW_ENABLED == 'true'
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.14"

      - name: Run build.py
        run: python build.py

      - name: Commit and push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Productive Work"
          git push
